name: Aristeas BranchDeletion
on:
  workflow_dispatch:
  delete:

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - id: local_DeleteMods
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"
          & "C:\actions-runner\externals\SC_NewUniversalUpload.exe" "deletebranch" "${{ github.event.ref }}"
