name: Aristeas ForceUploadAll
on:
  workflow_dispatch:

jobs:
  forceupload:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
    
      - id: local_forceUpload
        run: |
          & "C:\Program Files\SCUniversalUpload\SC_NewUniversalUpload.exe" "uploadall" --repo "${{ github.workspace }}"

      - uses: EndBug/add-and-commit@v9
